// <auto-generated />
namespace SharedPlaylistApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class refactoredmodelintoportableclasslibrary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoredmodelintoportableclasslibrary));
        
        string IMigrationMetadata.Id
        {
            get { return "201508010850167_refactored model into portable class library"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
