// <auto-generated />
namespace SharedPlaylistApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addedusernamefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedusernamefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201507311033162_Added username field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
